-- begin GANTT_SEGMENT2
alter table GANTT_SEGMENT2 add constraint FK_GANTT_SEGMENT2_ON_TASK_SPAN2 foreign key (TASK_SPAN2_ID) references GANTT_TASK_SPAN2(ID)^
create index IDX_GANTT_SEGMENT2_ON_TASK_SPAN2 on GANTT_SEGMENT2 (TASK_SPAN2_ID)^
-- end GANTT_SEGMENT2
